<a href="https://colab.research.google.com/github/vrinda518/NLP/blob/main/Sentiment_analysis_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### LOADING THE DATASET

In [7]:
import pandas as pd
df = pd.read_csv("friends.csv")
print(df.head())

                                               Scene Sentiment
0  {Monica} How about, you’re moving!! {Rachel} L...  NEGATIVE
1  {Phoebe} Or we could just follow your clever j...   NEUTRAL
2  {Joey} Hey Rach! Hey, you mind if I read my co...  NEGATIVE
3  {Joey} You forget how many great songs Heart h...   NEUTRAL
4  {Chandler} Hey Joe! You wanna shoot some hoops...   POSTIVE


In [8]:
labels = []
for sent in df['Sentiment']:
  if sent == 'NEGATIVE':
    labels.append(0.0)
  elif sent == 'POSTIVE':
    labels.append(1.0)
  else:
    labels.append(2.0)
df["labels"] = labels

In [9]:
df.head()
y = df.iloc[:,-1]

### DATA PREPROCESSING

In [10]:
index_names=df[df['Sentiment']=='MIXED'].index
df=df.drop(index_names)

In [11]:
df['Sentiment'].unique()

array(['NEGATIVE', 'NEUTRAL', 'POSTIVE'], dtype=object)

In [12]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.


True

In [13]:
import re
def  clean_text(df, text_field, new_text_field_name):
    df[new_text_field_name] = df[text_field].str.lower()
    df[new_text_field_name] = df[new_text_field_name].apply(lambda elem: re.sub(r"(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|^rt|http.+?", "", elem))  
    df[new_text_field_name] = df[new_text_field_name].apply(lambda elem: re.sub(r"\d+", "", elem)) 
    return df
data_clean = clean_text(df, 'Scene', 'Scene_Clean')
data_clean.head()

Scene  ...                                        Scene_Clean
0  {Monica} How about, you’re moving!! {Rachel} L...  ...  monica how about youre moving rachel look this...
1  {Phoebe} Or we could just follow your clever j...  ...  phoebe or we could just follow your clever jok...
2  {Joey} Hey Rach! Hey, you mind if I read my co...  ...  joey hey rach hey you mind if i read my comic ...
3  {Joey} You forget how many great songs Heart h...  ...  joey you forget how many great songs heart had...
4  {Chandler} Hey Joe! You wanna shoot some hoops...  ...  chandler hey joe you wanna shoot some hoops jo...

[5 rows x 4 columns]

In [14]:
from nltk import word_tokenize
clean_tokens = [word_tokenize(sent) for sent in df['Scene_Clean']]

In [15]:
print(clean_tokens)

[['monica', 'how', 'about', 'youre', 'moving', 'rachel', 'look', 'this', 'is', 'ridiculous', 'we', 'should', 'be', 'packing', 'you', 'phoebe', 'hey', 'how', 'are', 'you', 'guys', 'doing', 'rachel', 'great', 'monicas', 'moving', 'monica', 'i', 'am', 'not', 'rachel', 'oh', 'really', 'then', 'how', 'come', 'all', 'your', 'stuff', 'is', 'in', 'this', 'box', 'phoebe', 'okay', 'you', 'guys', 'you', 'guys', 'i', 'think', 'i', 'know', 'whats', 'going', 'on', 'here', 'okay', 'you', 'guys', 'monica', 'no', 'phoebe', 'i', 'am', 'mad', 'phoebe', 'well', 'deepdeepdeep', 'down', 'rachel', 'yeah', 'im', 'just', 'mad', 'phoebe', 'then', 'keep', 'running'], ['phoebe', 'or', 'we', 'could', 'just', 'follow', 'your', 'clever', 'jokes', 'any', 'ideas'], ['joey', 'hey', 'rach', 'hey', 'you', 'mind', 'if', 'i', 'read', 'my', 'comic', 'books', 'in', 'here', 'rachel', 'sure', 'why', 'joey', 'oh', 'well', 'chandler', 'and', 'monica', 'are', 'over', 'there', 'and', 'its', 'kinda', 'hard', 'to', 'concentrate', 'r

In [16]:
from nltk import PorterStemmer
porter = PorterStemmer()
stemmed_tokens = [[porter.stem(token) for token in l] for l in clean_tokens]
print(stemmed_tokens)

[['monica', 'how', 'about', 'your', 'move', 'rachel', 'look', 'thi', 'is', 'ridicul', 'we', 'should', 'be', 'pack', 'you', 'phoeb', 'hey', 'how', 'are', 'you', 'guy', 'do', 'rachel', 'great', 'monica', 'move', 'monica', 'i', 'am', 'not', 'rachel', 'oh', 'realli', 'then', 'how', 'come', 'all', 'your', 'stuff', 'is', 'in', 'thi', 'box', 'phoeb', 'okay', 'you', 'guy', 'you', 'guy', 'i', 'think', 'i', 'know', 'what', 'go', 'on', 'here', 'okay', 'you', 'guy', 'monica', 'no', 'phoeb', 'i', 'am', 'mad', 'phoeb', 'well', 'deepdeepdeep', 'down', 'rachel', 'yeah', 'im', 'just', 'mad', 'phoeb', 'then', 'keep', 'run'], ['phoeb', 'or', 'we', 'could', 'just', 'follow', 'your', 'clever', 'joke', 'ani', 'idea'], ['joey', 'hey', 'rach', 'hey', 'you', 'mind', 'if', 'i', 'read', 'my', 'comic', 'book', 'in', 'here', 'rachel', 'sure', 'whi', 'joey', 'oh', 'well', 'chandler', 'and', 'monica', 'are', 'over', 'there', 'and', 'it', 'kinda', 'hard', 'to', 'concentr', 'rachel', 'what', 'rachel', 'she', 'just', '

In [17]:
stemmed_list = []
for l in stemmed_tokens:
  stemmed_list.append(' '.join(l))
print(stemmed_list)

['monica how about your move rachel look thi is ridicul we should be pack you phoeb hey how are you guy do rachel great monica move monica i am not rachel oh realli then how come all your stuff is in thi box phoeb okay you guy you guy i think i know what go on here okay you guy monica no phoeb i am mad phoeb well deepdeepdeep down rachel yeah im just mad phoeb then keep run', 'phoeb or we could just follow your clever joke ani idea', 'joey hey rach hey you mind if i read my comic book in here rachel sure whi joey oh well chandler and monica are over there and it kinda hard to concentr rachel what rachel she just call and said that she wa gon na be work late rachel she keep lie to me rachel that it rachel im just gon na go over there and confront them right now', 'joey you forget how mani great song heart had chandler yeah ross you know barracuda wa the first song i learn to play on the keyboard chandler so you heard it you repeat it so that must mean you wrote it joey oh you guy with t

In [18]:
df["cleaned"] = stemmed_list

In [19]:
print(df.head())

                                               Scene  ...                                            cleaned
0  {Monica} How about, you’re moving!! {Rachel} L...  ...  monica how about your move rachel look thi is ...
1  {Phoebe} Or we could just follow your clever j...  ...  phoeb or we could just follow your clever joke...
2  {Joey} Hey Rach! Hey, you mind if I read my co...  ...  joey hey rach hey you mind if i read my comic ...
3  {Joey} You forget how many great songs Heart h...  ...  joey you forget how mani great song heart had ...
4  {Chandler} Hey Joe! You wanna shoot some hoops...  ...  chandler hey joe you wan na shoot some hoop jo...

[5 rows x 5 columns]


### COUNT VECTORIZER

In [20]:
from sklearn.feature_extraction.text import CountVectorizer,ENGLISH_STOP_WORDS
stop = ENGLISH_STOP_WORDS.union(['phoebe','monica','chandler','rachel','joey','ross','rach'])
cv = CountVectorizer(ngram_range = (1,2),stop_words = stop,max_features=5000)
cv.fit_transform(df['cleaned'])
bow = cv.transform(df['cleaned'])
print(bow.toarray())
X_df = pd.DataFrame(bow.toarray(), columns=cv.get_feature_names())
print(X_df.head())
##print(X_df['rach'])

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
   abbey  abl  absolut  accent  accid  ...  youyou  youyouy  zane  zelner  zoo
0      0    0        0       0      0  ...       0        0     0       0    0
1      0    0        0       0      0  ...       0        0     0       0    0
2      0    0        0       0      0  ...       0        0     0       0    0
3      0    0        0       0      0  ...       0        0     0       0    0
4      0    0        0       0      0  ...       0        0     0       0    0

[5 rows x 5000 columns]


In [21]:
y = df.iloc[:,2]

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X_df,y,test_size=0.2,random_state=92)

In [23]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(penalty='l2',C = 1)
log_reg = lr.fit(X_train,y_train)

In [24]:
from sklearn.metrics import confusion_matrix, accuracy_score
y_pred = log_reg.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(accuracy_score(y_test,y_pred))

[[44 10 15]
 [14 21 17]
 [24  8 35]]
0.5319148936170213


### TfIdf

In [25]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(stop_words = stop)
vect = tf.fit(df['cleaned'])
bowtf = tf.transform(df['cleaned'])
print(bowtf.toarray())
X_tf = pd.DataFrame(bowtf.toarray(), columns=tf.get_feature_names())
print(X_tf)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
      aa  aaargh  aahah  aaron  abandon  ...  zillionair  zinfandel  zip  zone  zoo
0    0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
1    0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
2    0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
3    0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
4    0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
..   ...     ...    ...    ...      ...  ...         ...        ...  ...   ...  ...
935  0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
936  0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
937  0.0     0.0    0.0    0.0      0.0  ...         0.0        0.0  0.0   0.0  0.0
938 

In [26]:
X_train2,X_test2,y_train2,y_test2 = train_test_split(X_tf,y,test_size=0.2,random_state=92)

In [27]:
log_reg2 = lr.fit(X_train2,y_train2)
y_pred2 = log_reg2.predict(X_test2)
print(confusion_matrix(y_test2,y_pred2))
print(accuracy_score(y_test2,y_pred2))

[[54  2 13]
 [23  7 22]
 [31  3 33]]
0.5
